version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/Console-log
    overwrite: yes
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ec2-user/Console-log
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
  #      runas: ec2-user

  AfterInstall:
    - location: scripts/deploy.sh
      runas: ec2-user